[deps]
ModelOrderReduction = "207801d6-6cee-43a9-ad0c-f0c64933efa0"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"

[compat]
ModelOrderReduction = "1"
ModelingToolkit = "11"
OrdinaryDiffEq = "7"
SymbolicIndexingInterface = "0.3"
